### ISSUE TITLE
The ability to organize sites by folder or tags

### ISSUE THREAD

**Issue by DanSman** [afollestad/nock-nock#13]
Hi,

A folder option would be great. To get the list more sorted. That you don't have to scroll it ... the whole list. Like 'server 1'. .. or 'company 1', 'company 2' etc.

But actually, the app is already really helpful and nice!
Thanks

**Comment by johnjohndoe** [comment]
How about tags instead of folders? They can be used to organize/categorize items as they like.

**Comment by DanSman** [comment]
Hm... but the list can be really long. What about both? ;) 
And moveable would be great too. If you forget to put one of your favorites on top of the list.
