### ISSUE TITLE
HTTP Errors crash the app

### ISSUE THREAD

**Issue by JaxonWright** [afollestad/nock-nock#41]
Since the rewrite, it seems like whenever I get an error response while inside of the app, it crashes.

**Comment by afollestad** [comment]
Interesting - I haven't experienced that yet

**Comment by afollestad** [comment]
@JaxonWright do you have a quick way to repro this?

**Comment by JaxonWright** [comment]
I can't seem to reproduce it anymore. 🤔

**Comment by afollestad** [comment]
Weird 😂
