### ISSUE TITLE
F-Droid submission has No Source Since: 0.8.2

### ISSUE THREAD

**Issue by ds6** [afollestad/nock-nock#45]
https://f-droid.org/en/packages/com.afollestad.nocknock/
https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.afollestad.nocknock.txt#L45

**Comment by afollestad** [comment]
I didn't setup F-Droid and don't maintain the project there.

**Comment by ds6** [comment]
Didn't check the commit history, since this situation is uncommon. Excuse me.
You should consider doing so however; F-Droid is a great platform. It only takes updating the repo and the build bot will take care of the rest, i.e. not having to upload prebuilt apks.
