### ISSUE TITLE
Crash occurs while removing headers.

### ISSUE THREAD

**Issue by Johnett** [afollestad/nock-nock#48]
**App Version:**

0.8.7 
 
**Affected Device(s):**
 
Nexus 5X with Android 7.1.1(in AVD)
Samsung Galaxy S6 edge plus with Android 7.0
Nexus 6 with Android 9.0(in AVD)
 
**Describe the Bug:**

I added more than one header. After that, I remove the first one and the last one. Then the app got crashed.

**To Reproduce:**
1. First, add more than four headers.
2. Remove any header other than last two.
3. Then try to remove any of the last two.

Screenshots -----

<img src="https://user-images.githubusercontent.com/25472210/55148735-c97a5200-516e-11e9-89c9-d3407e13669c.png" data-canonical-src="https://user-images.githubusercontent.com/25472210/55148735-c97a5200-516e-11e9-89c9-d3407e13669c.png" width="350" height="667" />

<img src="https://user-images.githubusercontent.com/25472210/55149286-e6fbeb80-516f-11e9-9dd5-2480608d3447.png" data-canonical-src="https://user-images.githubusercontent.com/25472210/55149286-e6fbeb80-516f-11e9-9dd5-2480608d3447.png" width="950" height="667" />

**Expected Behavior:**

The header should be removed without the crash.

**Error Log:**

 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.afollestad.nocknock, PID: 2635
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.unFocus(android.view.View)' on a null object reference
        at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4702)
        at android.view.ViewGroup.removeViewAt(ViewGroup.java:4665)
        at com.afollestad.nocknock.viewcomponents.headers.HeaderStackLayout.onClick(HeaderStackLayout.kt:59)
        at android.view.View.performClick(View.java:5637)
        at android.view.View$PerformClick.run(View.java:22429)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by realrufans** [comment]
Hello @Johnett, how did you get the logcat? I need help on how to generate logcat on a non rooted device. Thanks.

**Comment by Johnett** [comment]
Hellow @realrufans Could you be more specific. Do you know how to use Logcat(Android Studio feature) for any application(whether it is rooted or non-rooted)?

**Comment by realrufans** [comment]
Okay let's forget about rooting a device m
So I should learn how to get logcat from Android studio? 
Do I have to fork the repo ? So as to get it running on my android studio? Then get the logcat?
Or I don't need the project files , just the app installed?

**Comment by Johnett** [comment]
If it(the apk) is a debugging(probably created by android studio 'build apk' option) version you don't need to fork the repo just run the application on your device and connect it using ADB you are all set. If it is production version(probably installed from play store) it's very hard to see the logs. In production, the developers hide most logs.

**Comment by realrufans** [comment]
Okay thanks 👌

**Comment by Johnett** [comment]
If you are not familiar with Logcat I can give you some instructions.

**Comment by realrufans** [comment]
I have always been taking bug reports from this feature on my device. 
![Screenshot_20190408-090207.png](https://cdn.steemitimages.com/DQmWp25uXKkMeLT45knvbFzfNJyZJ2f5XyiCuYvfzPvy3zc/Screenshot_20190408-090207.png)

But, what it does is, take the whole system reports, including apps I don't wanna share. The report format is in zip format. In the zip file, there's a logcat.txt file, but it's dammmnn difficult to locate the app at actually crashed.
 So I need a simpler way to get short and exact logcat, just as you did up there.

**Comment by Johnett** [comment]
Are you a developer or tester(QA or Security testing)?

**Comment by realrufans** [comment]
QA tester.
And, I'm just learning kotlin, hoping I will start developing soon.

**Comment by Johnett** [comment]
Okay, thanks for the information. From the details you've provided, I can definitely say that you must learn how to use Logcat it would be a great tool for your job(because you can mention the bug more precisely).

For this(report this issue) I just did the following thing. I forked the repository and I just run it on my device. First I ensured I can reproduce the bug, Then I open the Logcat as follows.

![screen1](https://user-images.githubusercontent.com/25472210/55709886-f3513580-5a06-11e9-944c-7cce53113503.png)

If you can't locate Logcat here(see the above image) you can open it as follows or you can use the keyboard short cut(Alt + 6) in Windows.

![screen2](https://user-images.githubusercontent.com/25472210/55709989-33b0b380-5a07-11e9-9576-307ee6771ff0.png)

From the Logcat window first you have to select the device(If it's not selected already) you are running the application.


![screen4](https://user-images.githubusercontent.com/25472210/55710126-89855b80-5a07-11e9-84fb-f80896b15ab2.png)

Then you have to select the app you are testing(If it's not selected already).

![screen5](https://user-images.githubusercontent.com/25472210/55710244-d406d800-5a07-11e9-94f2-c313c9e13286.png)

After that, you have to select what kind of log you want to see.

![screen6](https://user-images.githubusercontent.com/25472210/55710302-fe589580-5a07-11e9-8b99-6c6210da1048.png)

Finally, you have to select the filtering option as below.

![screen7](https://user-images.githubusercontent.com/25472210/55710416-3364e800-5a08-11e9-90ac-5ffc0eadb11a.png)

Hope its helped a bit.

**Comment by realrufans** [comment]
Omg! Thank you! It's a million helpful. Wow thanks

**Comment by Johnett** [comment]
You are welcome, friend.
