### ISSUE TITLE
App crashes after clearing the whole values entered for  Check intervals, and Network Response Timeout.

### ISSUE THREAD

**Issue by realrufans** [afollestad/nock-nock#49]
## Expected behavior

I expected it not to crash, after users clears their input

## Actual behavior

 The app crashes after a user clears all the inputted value(s).

## How to reproduce
- launch Nock Nock
- Click on add site 
- Enter an input for **Check Interval**, or **Network Response Timeout**
- clear the values entered (Everything)
- see it crashing

**Note:** It doesn't crash if everything isn't cleared. For example; enter **12**, clear only **2**, the app won't crash. But, it will crash just after clearing the remaining input which is **1**.

# Screenshot/Gif

![cu4u547n2h.gif](https://img.esteem.ws/cu4u547n2h.gif)

## Devices
Device: Tecno Camon Xpro
OS: Android
Version 8.1

**Comment by afollestad** [comment]
Are you running an old version of the app? This was fixed a long time ago - unable to reproduce on my end to.

**Comment by realrufans** [comment]
I'm on V0.8.1

**Comment by realrufans** [comment]
Omg!! Latest is 0.8.3
