### ISSUE TITLE
Current version can't be added to F-Droid because of proprietary dependencies

### ISSUE THREAD

**Issue by qwertychouskie** [afollestad/nock-nock#55]
As per https://gitlab.com/fdroid/fdroiddata/issues/1708#note_196565158, the current version can't be added to F-Droid without some kind of build option to disable these proprietary dependencies.  I'd love if this could be resolved so I could use the latest version.  :)

**Comment by afollestad** [comment]
Sorry, I'm not prioritizing F-Droid at all.
