### ISSUE TITLE
F-Droid inclusion?

### ISSUE THREAD

**Issue by relan** [afollestad/nock-nock#6]
Hi,

I'd like to see Nock Nock on [F-Droid](https://f-droid.org/). Are you OK with this? Nothing to do on your side, only your permission is required.

**Comment by afollestad** [comment]
Sure, that's fine

**Comment by relan** [comment]
Great! Added in https://gitlab.com/fdroid/fdroiddata/commit/402a574f68757c091965c5dfd6159d34cec1cc64
